pipeline {
    agent any
    stages {
        stage('---update---') {
            steps {
                sh 'sudo apt update '
            }
        }
        stage('--install--') {
            steps {
               sh ' sudo apt install -y nginx'
            }
        }
        stage('--run--') {
            steps {
               sh 'sudo systemctl start nginx'
            }
        }
        stage('--status--') {
            steps {
                sh 'sudo systemctl status nginx'
            }
        }
    }
}
