pipeline {
    agent any
    stages {
        stage('---update---') {
            steps {
                sh 'echo "apt update" '
            }
        }
        stage('--install--') {
            steps {
               sh ' echo " install "'
            }
        }
        stage('--run--') {
            steps {
               sh ' echo " run "'
            }
        }
        stage('--status--') {
            steps {
                sh 'echo " status "'
            }
        }
    }
}
